project:
  type: website
  output-dir: docs

website:
  title: "PSYC480 Open Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/usman-afzali/psyc480-2k24
      - icon: twitter
        href: https://twitter.com/UsmanAfzali
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

