project:
  type: website
  output-dir: docs

website:
  title: "PSYC480 Open Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://usman-afzali.github.io/psyc480-2024/
      - icon: twitter
        href: https://twitter.com/UsmanAfzali
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

